apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml --out k8s
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: detectron2
  name: detectron2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: detectron2
    spec:
      containers:
      - env:
        - name: BASE_ADDRESS
          value: backend:4000
        - name: FETCH_INTERVAL
          value: "10"
        image: imagestored/detectron2
        name: detectron2
        resources: {}
      restartPolicy: Always
status: {}
